pipeline {
   agent any

    stages {
        stage('Build') {
            steps {
               sh 'cd /var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/my_maven/bin/'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'pwd'
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
